/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 social.gltf --transform
Author: prhtkblender952 (https://sketchfab.com/prhtkblender952)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/social-networks-cf2636162f2c484ca183788f72f413b4
Title: Social Networks
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/social-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} position={[1.168, 1.448, 0.619]} rotation={[0.373, 0.011, 0.145]} scale={[0.618, 0.089, 0.618]} />
      <mesh geometry={nodes.Object_72.geometry} material={materials['Material.010']} position={[3.402, 1.435, 1.136]} rotation={[-1.373, -0.238, -0.043]} scale={[0.658, 0.698, 0.084]} />
    </group>
  )
}

useGLTF.preload('/social-transformed.glb')
