/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 website.gltf --transform
Author: quaternius (https://sketchfab.com/quaternius)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ultimate-platformer-pack-100-models-8e016bc1b79f4c6aa58d430daa299f1e
Title: Ultimate Platformer Pack (100+ Models)
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/website-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Root" position={[0, 0, -0.079]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="CharacterArmature" position={[-13.279, -3.128, -0.028]}>
            <primitive object={nodes.CharacterArmature_rootJoint} />
            <skinnedMesh name="Arms_0" geometry={nodes.Arms_0.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Arms_0.skeleton} />
            <skinnedMesh name="Arms_1" geometry={nodes.Arms_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Arms_1.skeleton} />
            <skinnedMesh name="Body_0" geometry={nodes.Body_0.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Body_0.skeleton} />
            <skinnedMesh name="Body_1" geometry={nodes.Body_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Body_1.skeleton} />
            <skinnedMesh name="Body_2" geometry={nodes.Body_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Body_2.skeleton} />
            <skinnedMesh name="Ears_0" geometry={nodes.Ears_0.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Ears_0.skeleton} />
            <skinnedMesh name="Head_0" geometry={nodes.Head_0.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Head_0.skeleton} />
            <skinnedMesh name="Head_1" geometry={nodes.Head_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Head_1.skeleton} />
            <skinnedMesh name="Head_2" geometry={nodes.Head_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Head_2.skeleton} />
            <skinnedMesh name="Head_3" geometry={nodes.Head_3.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Head_3.skeleton} />
            <skinnedMesh name="Head_4" geometry={nodes.Head_4.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Head_4.skeleton} />
          </group>
          <group name="MonsterArmature003" position={[-13.01, 7.164, 3.901]}>
            <primitive object={nodes.MonsterArmature003_rootJoint} />
            <skinnedMesh name="Enemy_Body_0" geometry={nodes.Enemy_Body_0.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Enemy_Body_0.skeleton} />
            <skinnedMesh name="Enemy_Body_1" geometry={nodes.Enemy_Body_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Enemy_Body_1.skeleton} />
            <skinnedMesh name="Enemy_Eyes_0" geometry={nodes.Enemy_Eyes_0.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Enemy_Eyes_0.skeleton} />
            <skinnedMesh name="Enemy_Face_0" geometry={nodes.Enemy_Face_0.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Enemy_Face_0.skeleton} />
            <skinnedMesh name="Enemy_Face_1" geometry={nodes.Enemy_Face_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Enemy_Face_1.skeleton} />
            <skinnedMesh name="Enemy_Face_2" geometry={nodes.Enemy_Face_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Enemy_Face_2.skeleton} />
            <skinnedMesh name="Enemy_Face_3" geometry={nodes.Enemy_Face_3.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Enemy_Face_3.skeleton} />
          </group>
          <group name="MonsterArmature001" position={[-1.237, 1.15, -0.029]}>
            <primitive object={nodes.MonsterArmature001_rootJoint} />
            <skinnedMesh name="Crab_0" geometry={nodes.Crab_0.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Crab_0.skeleton} />
            <skinnedMesh name="Crab_1" geometry={nodes.Crab_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Crab_1.skeleton} />
            <skinnedMesh name="Crab_2" geometry={nodes.Crab_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Crab_2.skeleton} />
            <skinnedMesh name="Crab_3" geometry={nodes.Crab_3.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Crab_3.skeleton} />
          </group>
          <group name="MonsterArmature" position={[8.512, -0.079, 0.395]}>
            <primitive object={nodes.MonsterArmature_rootJoint} />
            <skinnedMesh name="Bee_0" geometry={nodes.Bee_0.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Bee_0.skeleton} />
            <skinnedMesh name="Bee_1" geometry={nodes.Bee_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Bee_1.skeleton} />
            <skinnedMesh name="Bee_2" geometry={nodes.Bee_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Bee_2.skeleton} />
            <skinnedMesh name="Bee_3" geometry={nodes.Bee_3.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Bee_3.skeleton} />
            <skinnedMesh name="Bee_4" geometry={nodes.Bee_4.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Bee_4.skeleton} />
            <skinnedMesh name="Bee_5" geometry={nodes.Bee_5.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Bee_5.skeleton} />
          </group>
          <group name="Gem_Pink" position={[-9.573, 10.337, 1.096]}>
            <mesh name="Gem_Pink_0" geometry={nodes.Gem_Pink_0.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Gem_Green" position={[-9.588, 6.297, 1.159]}>
            <mesh name="Gem_Green_0" geometry={nodes.Gem_Green_0.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cloud_3" position={[-14.026, -9.755, -2.56]} rotation={[0, 0, 0.719]}>
            <mesh name="Cloud_3_0" geometry={nodes.Cloud_3_0.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cloud_2" position={[11.853, 19.056, 1.215]} rotation={[0, 0, 0.556]}>
            <mesh name="Cloud_2_0" geometry={nodes.Cloud_2_0.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cloud_1" position={[-8.639, 24.922, 1.798]} rotation={[-0.087, 0.106, 0.689]}>
            <mesh name="Cloud_1_0" geometry={nodes.Cloud_1_0.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Chest_Armature" position={[1.01, -10.91, -3.614]}>
            <primitive object={nodes.Chest_Armature_rootJoint} />
            <skinnedMesh name="Chest_Bottom_0" geometry={nodes.Chest_Bottom_0.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Chest_Bottom_0.skeleton} />
            <skinnedMesh name="Chest_Bottom_1" geometry={nodes.Chest_Bottom_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Chest_Bottom_1.skeleton} />
            <skinnedMesh name="Chest_Bottom_2" geometry={nodes.Chest_Bottom_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Chest_Bottom_2.skeleton} />
            <skinnedMesh name="Chest_Bottom_3" geometry={nodes.Chest_Bottom_3.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Chest_Bottom_3.skeleton} />
            <skinnedMesh name="Chest_Bottom_4" geometry={nodes.Chest_Bottom_4.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Chest_Bottom_4.skeleton} />
            <skinnedMesh name="Chest_Top_0" geometry={nodes.Chest_Top_0.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Chest_Top_0.skeleton} />
            <skinnedMesh name="Chest_Top_1" geometry={nodes.Chest_Top_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Chest_Top_1.skeleton} />
            <skinnedMesh name="Chest_Top_2" geometry={nodes.Chest_Top_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Chest_Top_2.skeleton} />
          </group>
          <group name="BouncerArmature" position={[-9.409, 14.205, -0.072]}>
            <primitive object={nodes.BouncerArmature_rootJoint} />
            <skinnedMesh name="Bouncer_0" geometry={nodes.Bouncer_0.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Bouncer_0.skeleton} />
            <skinnedMesh name="Bouncer_1" geometry={nodes.Bouncer_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Bouncer_1.skeleton} />
          </group>
          <group name="Cube_Bricks005" position={[7.198, 11.728, -1.911]} rotation={[0, 0, Math.PI / 2]}>
            <mesh name="Cube_Bricks005_0" geometry={nodes.Cube_Bricks005_0.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Coin001" position={[-9.431, 14.256, 2.519]}>
            <mesh name="Coin001_0" geometry={nodes.Coin001_0.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Star001" position={[6.591, 23.398, 3.374]} rotation={[0, 0, 0.719]}>
            <mesh name="Star001_0" geometry={nodes.Star001_0.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cloud_1001" position={[-23.477, -2.241, 3.182]} rotation={[-0.043, -0.248, -2.372]}>
            <mesh name="Cloud_1001_0" geometry={nodes.Cloud_1001_0.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cloud_3001" position={[17.719, -1.305, -5.006]}>
            <mesh name="Cloud_3001_0" geometry={nodes.Cloud_3001_0.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cloud_2001" position={[11.062, -10.667, -2.647]} rotation={[0, 0, 0.531]}>
            <mesh name="Cloud_2001_0" geometry={nodes.Cloud_2001_0.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Coin003" position={[14.517, 8.533, 1.144]}>
            <mesh name="Coin003_0" geometry={nodes.Coin003_0.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="BouncerArmature001" position={[14.538, 8.485, -1.454]}>
            <primitive object={nodes.BouncerArmature001_rootJoint} />
            <skinnedMesh name="Bouncer001_0" geometry={nodes.Bouncer001_0.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Bouncer001_0.skeleton} />
            <skinnedMesh name="Bouncer001_1" geometry={nodes.Bouncer001_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Bouncer001_1.skeleton} />
          </group>
          <group name="Cube_Bricks001" position={[3.045, 14.013, -0.502]} rotation={[0, 0, Math.PI / 2]}>
            <mesh name="Cube_Bricks001_0" geometry={nodes.Cube_Bricks001_0.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="MonsterArmature002" position={[-4.237, 1.769, -0.029]}>
            <primitive object={nodes.MonsterArmature002_rootJoint} />
            <skinnedMesh name="Crab001_0" geometry={nodes.Crab001_0.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Crab001_0.skeleton} />
            <skinnedMesh name="Crab001_1" geometry={nodes.Crab001_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Crab001_1.skeleton} />
            <skinnedMesh name="Crab001_2" geometry={nodes.Crab001_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Crab001_2.skeleton} />
            <skinnedMesh name="Crab001_3" geometry={nodes.Crab001_3.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Crab001_3.skeleton} />
          </group>
        </group>
        <primitive object={nodes.Hazard_SpikeTrap_Armature_rootJoint} />
        <primitive object={nodes.Hazard_SpikeTrap_Armature001_rootJoint} />
        <primitive object={nodes.Hazard_SpikeTrap_Armature002_rootJoint} />
        <mesh name="Tree_Fruit_0" geometry={nodes.Tree_Fruit_0.geometry} material={materials.PaletteMaterial001} position={[-14.736, -0.469, 0.109]} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Hazard_SpikeTrap_0" geometry={nodes.Hazard_SpikeTrap_0.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Hazard_SpikeTrap_0.skeleton} position={[1.824, -2.164, 6.822]} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Hazard_SpikeTrap_1" geometry={nodes.Hazard_SpikeTrap_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Hazard_SpikeTrap_1.skeleton} position={[1.824, -2.164, 6.822]} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Hazard_SpikeTrap001_0" geometry={nodes.Hazard_SpikeTrap001_0.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Hazard_SpikeTrap001_0.skeleton} position={[-0.176, -2.164, 6.822]} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Hazard_SpikeTrap001_1" geometry={nodes.Hazard_SpikeTrap001_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Hazard_SpikeTrap001_1.skeleton} position={[-0.176, -2.164, 6.822]} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Hazard_SpikeTrap002_0" geometry={nodes.Hazard_SpikeTrap002_0.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Hazard_SpikeTrap002_0.skeleton} position={[1.824, -2.164, 4.822]} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Hazard_SpikeTrap002_1" geometry={nodes.Hazard_SpikeTrap002_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Hazard_SpikeTrap002_1.skeleton} position={[1.824, -2.164, 4.822]} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/website-transformed.glb')
